@echo off

:arg1

if [%1] == [dos] goto dos
if [%1] == [w32] goto w32

goto help

:dos

echo Configuring MineFlags for DOS/djgpp...
set AL_MAKEFILE=makefile.dos
goto fix

:w32

echo Configuring MineFlags for Windows/Mingw32...
set AL_MAKEFILE=makefile.win
goto fix

:help

echo.
echo Usage: fix platform 
echo.
echo Where platform is one of: dos, w32.
echo.
goto end

:fix

echo # generated by fix.bat > makefile
echo include %AL_MAKEFILE% >> makefile

goto done

:done

echo Done!

:end

set AL_MAKEFILE=
